### ISSUE TITLE
Don't sync description field on update (but do sync it on create)

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/magento#6]
It's not clear where we have a list of fields to sync (on Update), not Create. Is it the same list as on create? Are we syncing descriptions, etc?

**Comment by dunagan5887** [comment]
The same fields are communicated to Reverb whether the sync is an update or a create. You can see the fields in the method below:

Reverb_ReverbSync_Model_Mapper_Product::getListingWrapper()

Below is a sample json representing the data being communicated to Reverb:

{"title":"Blue Tank-top","sku":"Blue-Tank-top-24","description":"Blue Tank-top","condition":"Used","has_inventory":"1","inventory":"10000.0000","price":"89.0000"}

Note: field "has_inventory" is not on the product level; it is the System -> Configuration setting in System -> Configuration -> Reverb -> Reverb Configuration -> Reverb Default -> Has Inventory?
 This value will be communicated in the "has_inventory" field for every product in the system. The same applies for the "condition" field and the Reverb Default -> Condition setting

**Comment by skwp** [comment]
Ok thanks. We're actually going to need to take `description` out of the list for _updates_ (still good on create). Eventually we will want a flexible system where people can turn on or off the sync of different fields. So maybe we can hack that to start with some hardcoded lists:

fields_to_sync_on_update = ['title','price','condition','inventory']

eventually they can come from user settings. does this make sense?

**Comment by dunagan5887** [comment]
This will require somewhat of a refactor but shouldn't be bad. 

Instead of making the call

$listingWrapper = Mage::getModel('reverbSync/Mapper_Product')->getListingWrapper($product);

in method Reverb_ReverbSync_Helper_Sync_Product::executeIndividualProductDataSync() (legacy code issue) I will move the call into Reverb_ReverbSync_Helper_Data::createObject() or updateObject(). This will allow us to call specific getCreationListingWrapper() and getUpdateListingWrapper() depending on the necessary functionality

**Comment by skwp** [comment]
yep sounds good

**Comment by skwp** [comment]
Fixed in https://github.com/reverbdotcom/magento/commit/f68a9fafd28f3a178b90328add36be3948d59e9e
